### ISSUE TITLE
Generation problem of polymorphic type marshalling

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#698] opened 2021-09-22 11:17 UTC
## Problem
Some mgmt SDK generation code cannot pass build with marshalling or unmarshalling problem. The possible cause might be polymorphic type mixing up.
#### Error
.\zz_generated_models.go:3787:35: r.ResourceAttributes.marshalInternal undefined (type ResourceAttributes has no field or method marshalInternal)
#### Swagger
- https://github.com/Azure/azure-rest-api-specs/blob/3865f04d22e82db481be0727b406021d29cd2b70/specification/consumption/resource-manager/readme.md
#### Error
.\zz_generated_models.go:6141:71: too many arguments in call to m.MigrationValidationDatabaseLevelResult.marshalInternal
	have (string)
	want ()
.\zz_generated_models.go:6413:58: too many arguments in call to m.MigrationValidationResult.marshalInternal
	have (string)
	want ()
#### Swagger
- https://github.com/Azure/azure-rest-api-specs/blob/3865f04d22e82db481be0727b406021d29cd2b70/specification/datamigration/resource-manager/readme.md
#### Error
.\zz_generated_models.go:106:60: too many arguments in call to a.AksComputeSecretsProperties.marshalInternal
	have (ComputeType)
	want ()
.\zz_generated_models.go:1089:67: too many arguments in call to d.DatabricksComputeSecretsProperties.marshalInternal
	have (ComputeType)
	want ()
.\zz_generated_models.go:1509:49: too many arguments in call to k.KubernetesSchema.marshalInternal
	have (ComputeType)
	want ()
#### Swagger
- https://github.com/Azure/azure-rest-api-specs/blob/3865f04d22e82db481be0727b406021d29cd2b70/specification/machinelearningservices/resource-manager/readme.md

**Comment by jhendrixMSFT** [comment] 2021-09-23 00:28
Possible dupe of https://github.com/Azure/autorest.go/issues/652

**Comment by jhendrixMSFT** [comment] 2021-09-24 15:13
This is similar to #652 in that there are multiple parents.  However in this case neither of the parent types are discriminators.

**Comment by jhendrixMSFT** [comment] 2021-09-28 01:32
Fixed in preview.28

**Closed by jhendrixMSFT** 2021-09-28 01:32 UTC
Labels: CodeGen
